### ISSUE TITLE
IllegalArgumentException: Channel must contain : separator

### ISSUE THREAD

**Issue by mibby** [cnaude/VanishNoPacket#2]
I've been testing out a bunch of plugins in a new 1.13 environment to see what breaks. Just thought I'd let you know about this error for when you update to 1.13. :)

VanishNoPacket dev 27
https://h.cnaude.org/jenkins/job/VanishNoPacket/
Paper-1.13 dev 152 (Spigot 1.13)

Perhaps also merge with upstream VanishNoPacket?
```
[13:07:53] [Server thread/ERROR]: Error occurred while enabling VanishNoPacket v4.0-SNAPSHOT-unofficial (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator
	at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:209) ~[patched_1.13.jar:git-Paper-152]
	at org.kitteh.vanish.VanishManager.<init>(VanishManager.java:80) ~[?:?]
	at org.kitteh.vanish.VanishPlugin.onEnable(VanishPlugin.java:322) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[13:07:53] [Server thread/INFO]: [VanishNoPacket] Disabling VanishNoPacket v4.0-SNAPSHOT-unofficial
[13:07:53] [Server thread/ERROR]: Error occurred while disabling VanishNoPacket v4.0-SNAPSHOT-unofficial (Is it up to date?)
java.lang.NullPointerException: null
	at org.kitteh.vanish.VanishPlugin.onDisable(VanishPlugin.java:254) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by andrewkm** [comment]
Currently running build 32 via:
https://h.cnaude.org/jenkins/job/VanishNoPacket/32/

These issues seem to have been fixed. :)
