### ISSUE TITLE
IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by mibby** [cnaude/VanishNoPacket#3]
RE: https://github.com/cnaude/VanishNoPacket/issues/2

VanishNoPacket seems to spam this error on 1.13 as well.

```
[13:08:02] [Server thread/WARN]: [VanishNoPacket] Task #111 for VanishNoPacket v4.0-SNAPSHOT-unofficial generated an exception
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_181]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_181]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_181]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.jar:git-Paper-152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at org.kitteh.vanish.VanishManager$ShowPlayerHandler.run(VanishManager.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:979) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:915) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:813) ~[patched_1.13.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```

**Comment by andrewkm** [comment]
Currently running build 32 via:
https://h.cnaude.org/jenkins/job/VanishNoPacket/32/

These issues seem to have been fixed. :)
